export const dummyOrders = [
  {
    weightCategory: "0-5kg",
    customerName: "Amit Sharma",
    service: "Express Delivery",
    pickup: "Sector 18, Noida",
    dropoff: "Connaught Place, Delhi",
    paymentMethod: "upi",
    orderStatus: "pending",
    specialItems: "Fragile glass items",
    orderItem: ["Glass Vase", "Photo Frame"],
    reviews: ["64f1a9c1a1b2c3d4e5f607a1"],
  },
  {
    weightCategory: "5-10kg",
    customerName: "Priya Verma",
    service: "Standard Delivery",
    pickup: "Indiranagar, Bengaluru",
    dropoff: "Whitefield, Bengaluru",
    paymentMethod: "card",
    orderStatus: "processing",
    specialItems: "Handle with care",
    orderItem: ["Laptop", "Charger"],
    reviews: ["64f1a9c1a1b2c3d4e5f607a2", "64f1a9c1a1b2c3d4e5f607a3"],
  },
  {
    weightCategory: "10-20kg",
    customerName: "Rahul Mehta",
    service: "Same Day Delivery",
    pickup: "Andheri East, Mumbai",
    dropoff: "Borivali West, Mumbai",
    paymentMethod: "cash",
    orderStatus: "ready",
    orderItem: ["Office Chair"],
  },
  {
    weightCategory: "20-30kg",
    customerName: "Neha Kapoor",
    service: "Premium Delivery",
    pickup: "DLF Phase 3, Gurugram",
    dropoff: "Cyber City, Gurugram",
    paymentMethod: "online",
    orderStatus: "delivered",
    specialItems: "Heavy package",
    orderItem: ["Washing Machine"],
    reviews: ["64f1a9c1a1b2c3d4e5f607a4"],
  },
  {
    weightCategory: "0-5kg",
    customerName: "Suresh Kumar",
    service: "Economy Delivery",
    pickup: "Anna Nagar, Chennai",
    dropoff: "T Nagar, Chennai",
    paymentMethod: "cod",
    orderStatus: "cancelled",
  },
];
